package org.iii.www.util;
// Generated 2018/5/26 �U�� 08:45:16 by Hibernate Tools 5.3.0.Beta2

import org.iii.www.entity.Test0526Id;

/**
 * Test0526 generated by hbm2java
 */
public class Test0526 implements java.io.Serializable {

	private Test0526Id id;

	public Test0526() {
	}

	public Test0526(Test0526Id id) {
		this.id = id;
	}

	public Test0526Id getId() {
		return this.id;
	}

	public void setId(Test0526Id id) {
		this.id = id;
	}

}
